# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
  - page: 飞猪 Go
    url: /
    icon: home
  - page: 分类导航
    url: /categories/
    icon: bars
  - page: 涨点经验
    url: /projects/
    icon: angle-double-up
  - page: 攒点Bug
    url: /bugs/
    icon: bomb
  - page: 资源分享
    url: /share/
    icon: book
  - page: 工具
    url: /tools/
    icon: cog
  - page: 时间轴
    url: /archives/
    icon: 500px 

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: './img/head-img.jpg'
  url: 

# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends


## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## 网站公告设置
notification: |-
            <a class="fa fa-github" target="blank" href="https://github.com/shellingshord"> Github</a>
            <br>
            <a class="fa fa-paper-plane" href="mailto:shelling_@hotmail.com"> Mailto</a>
            

## 社交设置
social:
# - name: Github
#   icon: github
#   href: //github.com/shellingshord
# - name: 邮箱
#   icon: envelope-o
#   href: mailto:shelling_@hotmail.com

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   format: 'YYYY年MM月'
   show_count: true
   order: -1

## 标签云设置
tagcloud:
  tag3d: false
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## 友链设置
links:
#  - Hexo官网: https://hexo.io/zh-cn/


# 主题自定义个性化配置

## 网站宣传语
branding:

## 设置banner背景图片
banner:
    img: http://snippet.shenliyang.com/img/banner.jpg

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs: 
  -

## 截取文章首页描述字数
excerptLength: 50

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 3000
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      <img src='/img/wechat.png' style="width:66px;height:66px;float:right">

## 文章打赏
reward: 
  alipay: #'/img/alipay.png'
  wepay: #'/img/wechat.png'
  tip: #请博主喝一杯咖啡

## 主题评论

## Valine评论
valine:
   enable: true
   appId: xOKV9J4UeQAtVkvnJC7Kq2Jn-gzGzoHsz
   appKey: erIpQac4azoCmgfBB7Dl9maa
   placeholder: 说点什么吧
   notify: false
   verify: true
   avatar: mm
   meta: nick,mail
   pageSize: 10

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

## Gitalk评论
gitalk:
   enable: false
   clientID: 0e6a0fbf063cfc4125b6
   clientSecret: a750a414796db53a1def8fa68307388432e16da8
   repo:
   owner: shellingshord@hotmail.com
   admin: shellingshord@hotmail.com
   perPage: 5
   distractionFreeMode: true

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### gitment评论(长期不更新，不建议使用)
gitment:
  enable: false
  owner: shellingshord@hotmail.com
  repo:
  client_id: 0e6a0fbf063cfc4125b6
  client_secret: a750a414796db53a1def8fa68307388432e16da8
  perPage: 10

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422


## 网站访客统计
visit_counter:
   site: true
   page: true

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics: 1277780817

### 百度统计
baidu_analytics:

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: false

#网站主题配置
since: 2016-2019   fzg5_shelling
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.3
